git hooks

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,14 +1,20 @@
 #!/bin/bash
 
-bug_regex_commit_format='^AS:|^ML:|^MK:|^SL:'
-error_msg="Commit not allowed, message should have your initials while committing code"
+# save the file as <git_directory>/.git/hooks/pre-commit
 
-if ! grep -iqE "$bug_regex_commit_format" "$1"; then
-	echo "$error_msg" >&2
-	echo "Below are sample commits"
-	echo " AS: message"
-	echo " SL: message"
-	exit 1
-else
-	echo "Commit is successful"
+echo "Running Maven clean test for errors"
+# retrieving current working directory
+CWD=`pwd`
+MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+# go to main project dir
+cd $MAIN_DIR/../
+# running maven clean test
+mvn clean test
+if [ $? -ne 0 ]; then
+  "Error while testing the code"
+  # go back to current working dir
+  cd $CWD
+  exit 1
 fi
+# go back to current working dir
+cd $CWD
